### ISSUE TITLE
Filter changes: Specs.messages

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-frontend-assets#25]
https://github.com/RedHatInsights/insights-plugins/pull/769
~~~
INCIDENT = 'Failed to get disk info'
add_filter(Specs.messages, 'vmsvc')
~~~

**Comment by kylape** [comment]
This line is also below the two listed in the description here:

```
Messages.token_scan('failed_disk', INCIDENT)
```

Partially resolved in 6e7592df.  The incident line is not included in the filter list yet because `token_scan` functions are not picked up by the automated filter tool.  In general, please call `add_filter` along with all `token_scan` calls.

**Comment by kylape** [comment]
Nevermind, @csams pointed out to me that all log lines with the incident in them will also have the filter string.

**Comment by xiangce** [comment]
Thanks.
